import styles from "@/styles/pages/privacy.module.scss";
import Container from "@/app/components/Container";
import Label from "@/app/components/Label";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Affiliate Terms",
  description:
    "Review the official PubThrive Affiliate Program Terms and Conditions. Learn about commissions, eligibility, and payment policies for partners who refer publishers.",
  alternates: { canonical: "/affiliate-terms" },
  openGraph: {
    title: "Affiliate Terms | PubThrive",
    description:
      "Understand PubThrive’s Affiliate Program rules — commission structure, partner responsibilities, and payout details.",
    url: "https://pubthrive.com/affiliate-terms",
    type: "article",
    siteName: "PubThrive",
    images: ["/og.jpg"], // replace with your actual OG image
  },
  twitter: {
    card: "summary_large_image",
    title: "Affiliate Terms | PubThrive",
    description:
      "Read PubThrive’s Affiliate Terms to know your rights, earnings process, and compliance guidelines as a partner.",
    images: ["/og.jpg"],
  },
  robots: { index: true, follow: true },
};
export default function AffiliateTerms() {
  return (
    <main className={styles.page}>
      {/* HERO */}
      <section className={styles.hero}>
        <Container>
          <div className={styles.copy}>
            <Label text="Legal" color="#1900ff" />
            <h1 className={styles.h1}>Affiliate Program Terms</h1>
            <p className={styles.sub}>
              These Affiliate Terms explain how the PubThrive Affiliate Program
              works, what’s expected from affiliates, and how commissions and
              payouts are handled. By applying to or participating in our
              program, you agree to these terms.
            </p>
          </div>
        </Container>
      </section>
      <section className={styles.content}>
        <Container>
          <main>
            <section>
              <h2>1. Introduction</h2>
              <p>
                The PubThrive Affiliate Program (“Program”) is operated by
                PubThrive LLC (“PubThrive”, “we”, “us”, or “our”). The Program
                allows approved individuals or agencies (“Affiliates”, “you”) to
                earn commissions for bringing qualified publishers who join and
                monetize their traffic through PubThrive’s ad solutions.
              </p>
              <p>
                By joining the Program, you agree to comply with these Terms and
                all related PubThrive policies.
              </p>
            </section>

            <section>
              <h2>2. Eligibility</h2>
              <ul>
                <li>
                  Applicants must be at least 18 years of age and capable of
                  entering into binding agreements.
                </li>
                <li>
                  Affiliates may operate individually or as part of a registered
                  company or media network.
                </li>
                <li>
                  PubThrive reserves the right to approve, reject, or remove any
                  affiliate application without prior notice.
                </li>
              </ul>
            </section>

            <section>
              <h2>3. How the Program Works</h2>
              <p>
                The PubThrive Affiliate Program is a direct recruitment model —
                not based on URL tracking or automated cookies.
              </p>
              <ul>
                <li>
                  Affiliates refer or onboard new publishers by submitting their
                  details through the official affiliate form or direct
                  communication with PubThrive’s team.
                </li>
                <li>
                  Each referral is manually verified and approved by PubThrive’s
                  compliance department before activation.
                </li>
                <li>
                  Once a referred publisher starts earning through PubThrive,
                  the affiliate becomes eligible for commission according to the
                  approved revenue share plan.
                </li>
              </ul>
            </section>

            <section>
              <h2>4. Commission Structure</h2>
              <ul>
                <li>
                  Affiliates earn a commission based on the{" "}
                  <strong>net monthly revenue</strong> generated by their
                  referred publishers.
                </li>
                <li>
                  The percentage or flat commission rate is defined in the
                  affiliate’s onboarding agreement or confirmation email.
                </li>
                <li>
                  Commissions are calculated after traffic validation,
                  deductions for invalid activity, and network adjustments.
                </li>
                <li>
                  PubThrive may offer performance tiers or bonuses for
                  affiliates who exceed certain revenue or publisher-onboarding
                  thresholds.
                </li>
              </ul>
            </section>

            <section>
              <h2>5. Payment Terms</h2>
              <ul>
                <li>
                  Commissions are paid net-90 basis once the minimum payout
                  threshold ($100) is reached.
                </li>
                <li>
                  Payments are made in USD via Wise, Crypto or bank transfer.
                </li>
                <li>
                  Payouts are based on finalized publisher revenue after
                  PubThrive receives corresponding network settlements.
                </li>
                <li>
                  Affiliates are responsible for any transaction fees and
                  applicable taxes in their jurisdiction.
                </li>
              </ul>
            </section>

            <section>
              <h2>6. Affiliate Conduct</h2>
              <p>
                Affiliates must maintain professional and ethical conduct while
                representing PubThrive. You agree to:
              </p>
              <ul>
                <li>Promote PubThrive accurately and transparently.</li>
                <li>
                  Submit genuine and qualified publishers who comply with
                  PubThrive’s publisher requirements.
                </li>
                <li>
                  Provide truthful information about publisher ownership and
                  traffic sources.
                </li>
                <li>
                  Refrain from spamming, misleading claims, or impersonating
                  PubThrive representatives.
                </li>
              </ul>
              <p>
                Any attempt to manipulate referrals, submit fake sites, or
                misrepresent data will result in immediate termination and
                forfeiture of unpaid commissions.
              </p>
            </section>

            <section>
              <h2>7. Duplicate or Existing Publishers</h2>
              <p>
                Commissions will only be paid for new publishers not already in
                PubThrive’s database. If a referred site or publisher is already
                working with PubThrive, the referral will not qualify for
                commission.
              </p>
            </section>

            <section>
              <h2>8. Reporting and Verification</h2>
              <p>
                PubThrive provides affiliates with monthly summaries or
                dashboards showing approved publishers and estimated earnings.
                All reported data is subject to manual review, adjustment, and
                final approval before payment.
              </p>
            </section>

            <section>
              <h2>9. Termination</h2>
              <p>
                PubThrive may suspend or terminate your affiliate account at any
                time, with or without notice, for reasons including but not
                limited to:
              </p>
              <ul>
                <li>Violation of these Terms</li>
                <li>Fraudulent referrals or misrepresentation</li>
                <li>Inactive or unresponsive communication</li>
                <li>
                  Damage to PubThrive’s reputation or relationships with
                  partners
                </li>
              </ul>
              <p>
                You may terminate your participation at any time by emailing{" "}
                <a href="mailto:affiliates@pubthrive.com">
                  affiliates@pubthrive.com
                </a>
                .
              </p>
            </section>

            <section>
              <h2>10. Confidentiality</h2>
              <p>
                All business information shared by PubThrive — including
                publisher revenue data, payment terms, or partner relationships
                — is confidential and must not be disclosed or shared publicly.
              </p>
            </section>

            <section>
              <h2>11. Liability</h2>
              <p>
                PubThrive shall not be liable for any indirect, incidental, or
                consequential damages arising from participation in this
                Program. Our total liability shall not exceed the total
                commissions paid to the affiliate within the three months
                preceding any claim.
              </p>
            </section>

            <section>
              <h2>12. Program Changes</h2>
              <p>
                PubThrive reserves the right to update, pause, or discontinue
                the Affiliate Program or modify these Terms at any time. Updated
                versions will be published on this page with the revised date
                below. Continued participation constitutes acceptance of the
                updated terms.
              </p>
              <p>
                <em>Last Updated: November 2025</em>
              </p>
            </section>

            <section>
              <h2>13. Governing Law</h2>
              <p>
                These Terms are governed by the laws of the State of Michigan,
                United States. Any disputes shall be resolved exclusively in the
                courts of Michigan.
              </p>
            </section>
            <section>
              <h2 id="contact">12. Contact Us</h2>
              <address>
                <strong>PubThrive LLC</strong>
                405 W. Greenlawn Ave, Lansing, MI 48910, USA
                <br />
                Email:{" "}
                <a href="mailto:contact@pubthrive.com">contact@pubthrive.com</a>
                <br />
                Website:{" "}
                <a href="https://pubthrive.com" rel="noopener">
                  www.pubthrive.com
                </a>
              </address>
            </section>
          </main>
        </Container>
      </section>
    </main>
  );
}
